development:
  adapter: postgresql
  database: jeff_eiden_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: jeff_eiden_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: jeff_eiden_production
  pool: 5
  timeout: 5000
